version: '2'

volumes:
  content:
    external: true
    name: ${SLD}-stg-content
  content-prod:
    external: true
    name: ${SLD}-prod-content
  media:
    external: true
    name: ${SLD}-stg-media
  sessions:
    external: true
    name: ${SLD}-stg-sessions
  accounts:
    external: true
    name: ${SLD}-accounts
  cache-prod:
    external: true
    name: ${SLD}-prod-cache
services:
  stg:
    build: .
    image: wagnerpaul/${SLD}-main-app:stg
    volumes:
      - content:/app/content
      - content-prod:/app/content-prod
      - media:/app/public/media
      - cache-prod:/app/storage-prod/cache
      - sessions:/app/storage/sessions
      - accounts:/app/storage/accounts
    environment:
      SERVER_NAME: stg.${SLD}.${TLD}
      VIRTUAL_HOST: stg.${SLD}.${TLD}
      ENABLE_PANEL: 'true'
      ENABLE_PW: 'true'
      LETSENCRYPT_HOST: stg.${SLD}.${TLD}
      LETSENCRYPT_EMAIL: jeremy@korb.studio
    container_name: ${SLD}-stg
    restart: always
  backups-content-stg:
    image: blacklabelops/volumerize
    container_name: ${SLD}-content-backups-stg
    restart: unless-stopped
    volumes:
      - content:/content:ro
    environment:
      VOLUMERIZE_FULL_IF_OLDER_THAN: 1M
      VOLUMERIZE_SOURCE: /content
      VOLUMERIZE_TARGET: b2://${B2_ID}:${B2_KEY}@${B2_BUCKET}/${SLD}-backups/content-stg
  backups-accounts-stg:
    image: blacklabelops/volumerize
    container_name: ${SLD}-accounts-backups-stg
    restart: unless-stopped
    volumes:
      - accounts:/accounts:ro
    environment:
      VOLUMERIZE_FULL_IF_OLDER_THAN: 1M
      VOLUMERIZE_SOURCE: /accounts
      VOLUMERIZE_TARGET: b2://${B2_ID}:${B2_KEY}@${B2_BUCKET}/${SLD}-backups/accounts-stg
networks:
  default:
    name: proxy-network

